# Práctica 1: Resolución de SEL. Métodos directos. Método de Gauss

Utilizando la librería NumPy de Python podemos resolver sistemas de ecuaciones lineales. En concreto usando la función `solve` del módulo `linalg`. Importamos la librería y vemos cómo se utiliza:

In [1]:
import numpy as np

In [2]:
A=np.array([[2,4,1],[1,3,5],[-1,0,1]])
b=np.array([2,-5,1])

x = np.linalg.solve(A, b)
print(x)

[-2.86666667  2.4        -1.86666667]


Existe una función similar en la librería `SciPy`. Puedes investigar sobre el módulo `linalg` de `SciPy`.

### Resolución de sistemas sencillos

Si el sistema que se va a resolver es **triangular inferior**, se puede resolver fácilmente mediante sustitución hacia atrás. Implementamos la solución de este tipo de sistemas en Python.

In [3]:
def sust_regresiva(A,b):
    """
    Esta función resuelve el sistema Ax=b mediante sustitución regresiva. 
    A y b deben ser arrays de numpy. 
    A debe ser una matriz triangular superior.
    """
    A=A.astype(float)     # cambiamos los elementos a tipo flotante
    b=b.astype(float) 
    n=np.size(b)
    x=np.zeros(n)         # almacenaremos aquí la solución del sistema
                       
    # ahora se resuelve el sistema por sustitución regresiva
    x[n-1]=b[n-1]/A[n-1,n-1]
    for i in range(n-2,-1,-1):     
        x[i]=(b[i]-np.dot(A[i][i+1:],x[i+1:]))/A[i,i]
                
    return x

In [4]:
A=np.array([[1,2,3],[0,2,1],[0,0,5]])
b=np.array([1,5,2])
sust_regresiva(A,b)

array([-4.8,  2.3,  0.4])

In [5]:
np.linalg.solve(A, b)

array([-4.8,  2.3,  0.4])

**Ejercicio 1**: Escribe una función que resuelva por sustitución progresiva un sistema en el que la matriz de coeficientes es triangular inferior. Comprueba que se obtiene el mismo resultado utilizando dicha función que mediante la función `solve` de Numpy si lo aplicamos a las matrices 
$$A=\left(\begin{array}{rrr}
1 & 0 & 0 \\
2 & 2 & 0 \\
3 & 1 & 5 \end{array} \right) \qquad b=\left(2,5,1 \right) $$.

### Método de Gauss

Vamos a programar ahora el método de Gauss. Para esto podemos crear una función independiente o bien utilizar la función que hemos definido previamente. Aquí podéis observar cómo se crearía la función independiente para el método de Gauss sin intercambio de filas.

In [ ]:
def Gauss(A,b):
    """
    Esta función resuelve el sistema Ax=b mediante el método de Gauss. 
    A y b deben ser arrays de numpy.
    """
    A=A.astype(float)     # cambiamos los elementos a tipo flotante
    bb=(np.array([b]).transpose()).astype(float) 
    Ab=np.concatenate((A,bb),axis=1)
    n=np.size(b)
    x=np.zeros(n)         # almacenaremos aquí la solución del sistema
    
    # aquí se hacen operaciones por filas en la matriz para conseguir una triangular
    for i in range(n):
        if Ab[i,i]==0: sys.exit('Aparece una división por cero, el proceso no puede concluirse')
        else:
            for j in range(i+1,n):
                m=Ab[j,i]/Ab[i,i]
                Ab[j][i+1:]=Ab[j][i+1:]-m*Ab[i][i+1:]
                    
    # ahora se resuelve el sistema por sustitución regresiva
    x[n-1]=Ab[n-1,n]/Ab[n-1,n-1]
    for i in range(n-2,-1,-1):
        x[i]=(Ab[i,n]-np.dot(Ab[i][i+1:n],x[i+1:n]))/Ab[i,i]
                
    return x

In [ ]:
A=np.array([[2,4,1],[1,3,5],[-1,0,1]])
b=np.array([2,-5,1])
Gauss(A,b)

In [ ]:
A=np.array([[2,4,1],[1,3,5],[-1,0,1]])
b=np.array([2,-5,1])
np.linalg.solve(A, b)

Si se quiere utilizar la función que se ha definido previamente se puede hacer de la siguiente forma:

In [ ]:
def Gauss2(A,b):
    """
    Esta función resuelve el sistema Ax=b mediante el método de Gauss. 
    A y b deben ser arrays de numpy.
    """
    A=A.astype(float)     # cambiamos los elementos a tipo flotante
    bb=(np.array([b]).transpose()).astype(float) 
    Ab=np.concatenate((A,bb),axis=1)
    n=np.size(b)
       
    # aquí se hacen operaciones por filas en la matriz para conseguir una triangular
    for i in range(n):
        if Ab[i,i]==0: sys.exit('Aparece una división por cero, el proceso no puede concluirse')
        else:
            for j in range(i+1,n):
                m=Ab[j,i]/Ab[i,i]
                Ab[j]=Ab[j]-m*Ab[i]
                    
    # ahora se resuelve el sistema por sustitución regresiva
    AG=Ab[:,:n]
    bG=Ab[:,n].transpose()
    x=sust_regresiva(AG,bG)
                
    return x

In [ ]:
A=np.array([[2,4,1],[1,3,5],[-1,0,1]])
b=np.array([2,-5,1])
Gauss2(A,b)

**Ejercicio 2:** Modifica el código anterior para que resuelva SEL usando pivotaje parcial. Comprueba que el código funciona correctamente con las mismas matrices $A$ y $b$ del ejemplo anterior.