# Práctica 2: Resolución de SEL. Métodos directos. Factorización LU y de Cholesky

## Descomposición LU

En esta parte de la práctica veremos cómo hacer la factorización LU de una matriz en Python y la utilizaremos para resolver sistemas de ecuaciones lineales. En primer lugar, importamos la librería `NumPy`:

In [2]:
import numpy as np

Se puede calcular la descomposición LU de una matriz desde el módulo `linalg` de la librería `SciPy`. No necesitamos importar toda la librería así que importamos solamente las funciones `lu`,`lu_solve` y `lu_factor`  que vamos a necesitar.

In [3]:
from scipy.linalg import lu, lu_solve, lu_factor

In [4]:
A=np.array([[2,4,1],[1,3,5],[-1,0,1]])

P, L, U = lu(A)
print('P=', P)
print('L=', L)
print('U=', U)
print('LU=',np.dot(L, U))

P= [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
L= [[ 1.   0.   0. ]
 [-0.5  1.   0. ]
 [ 0.5  0.5  1. ]]
U= [[2.   4.   1.  ]
 [0.   2.   1.5 ]
 [0.   0.   3.75]]
LU= [[ 2.  4.  1.]
 [-1.  0.  1.]
 [ 1.  3.  5.]]


Al utilizar la función `lu` se hace la descomposición LU permitiendo permutaciones de filas. La salida consiste en tres matrices, una primera matriz **P** de permutaciones (se ha permutado la fila dos con la fila 3), la matriz **L** y la matriz **U**. Si observamos la matriz **L** del resultado, vemos que se ha realizado la descomposición LU de Doolittle. Observa la diferencia en las salidas si se usa `lu`o `lu_factor`.

In [5]:
A=np.array([[2,4,1],[1,3,5],[-1,0,1]])
lu(A)

(array([[1., 0., 0.],
        [0., 0., 1.],
        [0., 1., 0.]]),
 array([[ 1. ,  0. ,  0. ],
        [-0.5,  1. ,  0. ],
        [ 0.5,  0.5,  1. ]]),
 array([[2.  , 4.  , 1.  ],
        [0.  , 2.  , 1.5 ],
        [0.  , 0.  , 3.75]]))

In [6]:
A=np.array([[2,4,1],[1,3,5],[-1,0,1]])
lu_factor(A)

(array([[ 2.  ,  4.  ,  1.  ],
        [-0.5 ,  2.  ,  1.5 ],
        [ 0.5 ,  0.5 ,  3.75]]),
 array([0, 2, 2], dtype=int32))

En este segundo ejemplo aparecen las matrices **L** y **U** *mezcladas* en una única matriz. Esta descomposición se puede usar para resolver sistemas de la siguiente forma:

In [7]:
A=np.array([[2,4,1],[1,3,5],[-1,0,1]])
b=np.array([2,-5,1])

lu_solve(lu_factor(A),b)

array([-2.86666667,  2.4       , -1.86666667])

Vamos a proceder ahora a programar nosotros la descomposición LU de Doolittle sin intercambio de filas.

In [15]:
def LU_desc(A):
    """
    Esta función calcula la descomposición LU de Doolittle de una matriz A sin intercambio de filas.
    A debe ser un array de Numpy.
    """
    n=np.shape(A)[1]
    U=np.zeros([n,n])
    L=np.eye(n)
    
    for k in range(n-1):
        U[k,k]=A[k,k]-np.dot(L[k,:k],U[:k,k])
        for j in range(k+1,n):
            U[k,j]=A[k,j]-np.dot(L[k,:k],U[:k,j])
        for j in range(k+1):
            L[k+1,j]=(A[k+1,j]-np.dot(L[k+1,:j],U[:j,j]))/U[j,j]
    U[n-1,n-1]=A[n-1,n-1]-np.dot(L[n-1,:n-1],U[:n-1,n-1])
    return L, U

In [16]:
A=np.array([[2,4,1],[-1,0,1],[1,3,5]])
LU_desc(A)

(array([[ 1. ,  0. ,  0. ],
        [-0.5,  1. ,  0. ],
        [ 0.5,  0.5,  1. ]]),
 array([[2.  , 4.  , 1.  ],
        [0.  , 2.  , 1.5 ],
        [0.  , 0.  , 3.75]]))

**Ejercicio 1:** Utilizando la descomposición LU de esta práctica y las sustituciones progresiva y regresiva de la práctica anterior, resuelve el sistema $A x=b$ donde
$$A=\left(\begin{array}{rrr}
1 & 4 & 1 \\
1 & 3 & 5 \\
-2 & 0 & 1 \end{array} \right) \qquad b=\left(2,-5,1 \right) $$ 

## Descomposición de Cholesky

El módulo `linalg`de NumPy tiene implementada la descomposición de Cholesky. Observa los resultados que se obtienen en los dos ejemplos siguientes.

In [17]:
A=np.array([[2,4,1],[4,10,1],[1,1,5]])
np.linalg.cholesky(A)

array([[ 1.41421356,  0.        ,  0.        ],
       [ 2.82842712,  1.41421356,  0.        ],
       [ 0.70710678, -0.70710678,  2.        ]])

In [18]:
A=np.array([[2,4,1],[4,0,1],[1,1,5]])
np.linalg.cholesky(A)

LinAlgError: Matrix is not positive definite

**Ejercicio 2:** Define una función que resuelva un sistema de ecuaciones lineales mediante la factorización de Cholesky. Comprueba su funcionamiento para intentar resolver el sistema $A x=b$ donde $b=\left(2,-5,1 \right)$ en los casos de los ejemplos anteriores:
$$A=\left(\begin{array}{rrr}
2 & 4 & 1 \\
4 & 10 & 1 \\
1 & 1 & 5 \end{array} \right) \qquad 
A=\left(\begin{array}{rrr}
2 & 4 & 1 \\
4 & 0 & 1 \\
1 & 1 & 5 \end{array} \right)$$ 

**No** se permite utilizar la función `linalg.cholesky`de `NumPy`. Hay que modificar el código anterior de la factorización LU para definir una función que haga dicha factorización.
